# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'scanVC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'ZBarSDK', '~> 1.3.1' #扫描二维码，条形码




  # Pods for scanVC

  target 'scanVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
